version: '3.7'

services:
  web:
    build: ./
    container_name: django
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
#    depends_on:
#      - db
    environment:
      - X_FORWARDED_PROTO=https

#  db:
#    image: postgres:12
#    container_name: server_db
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - ./.env
#    ports:
#      - 5432:5432
#volumes:
#  postgres_data: