# Generated by Django 4.1.7 on 2023-06-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvotorOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, verbose_name='uuid')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код')),
                ('stores', models.CharField(max_length=200, verbose_name='Магазин')),
                ('role', models.CharField(max_length=100, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Эвотор Оператор',
                'verbose_name_plural': 'Эвотор Операторы',
            },
        ),
        migrations.CreateModel(
            name='EvotorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, verbose_name='UserID')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Эвотор токен',
                'verbose_name_plural': 'Эвотор токены',
            },
        ),
        migrations.CreateModel(
            name='EvotorUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, verbose_name='UserID')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Пользователи Эвотор',
                'verbose_name_plural': 'Пользователи Эвотор',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('bar_codes', models.JSONField(default=list)),
                ('alco_codes', models.JSONField(default=list)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('measure_name', models.CharField(max_length=50)),
                ('tax', models.CharField(max_length=50)),
                ('allow_to_sell', models.BooleanField()),
                ('description', models.TextField()),
                ('article_number', models.CharField(max_length=50)),
                ('parent_uuid', models.CharField(max_length=100)),
                ('group', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
                ('alcohol_by_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alcohol_product_kind_code', models.IntegerField()),
                ('tare_volume', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, verbose_name='uuid')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=200, null=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('store_uuid', models.CharField(blank=True, max_length=200, null=True, verbose_name='UUID магазина')),
                ('timezone_offset', models.IntegerField(blank=True, null=True, verbose_name='Смещение часового пояса')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
    ]
