# Generated by Django 4.1.7 on 2023-06-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Токен')),
                ('timestamp', models.BigIntegerField(verbose_name='Временная метка')),
                ('userId', models.CharField(max_length=255, verbose_name='Идентификатор пользователя')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('version', models.IntegerField(verbose_name='Версия')),
                ('deviceId', models.CharField(max_length=255, verbose_name='Идентификатор устройства')),
                ('storeId', models.CharField(max_length=255, verbose_name='Идентификатор магазина')),
                ('dateTime', models.DateTimeField(verbose_name='Дата и время')),
                ('shiftId', models.CharField(max_length=255, verbose_name='Идентификатор смены')),
                ('employeeId', models.CharField(max_length=255, verbose_name='Идентификатор сотрудника')),
                ('paymentSource', models.CharField(max_length=255, verbose_name='Источник оплаты')),
                ('infoCheck', models.BooleanField(verbose_name='Информационный чек')),
                ('egais', models.BooleanField(verbose_name='ЕГАИС')),
                ('totalTax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма налога')),
                ('totalDiscount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма скидки')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('extras', models.JSONField(verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='alco_codes',
            field=models.JSONField(default=list, verbose_name='Алкокоды'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alcohol_by_volume',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Крепость алкоголя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alcohol_product_kind_code',
            field=models.IntegerField(verbose_name='Код вида алкогольной продукции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_to_sell',
            field=models.BooleanField(verbose_name='Разрешено к продаже'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.CharField(max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bar_codes',
            field=models.JSONField(default=list, verbose_name='Штрих-коды'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.BooleanField(verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_name',
            field=models.CharField(max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_uuid',
            field=models.CharField(max_length=100, verbose_name='Идентификатор родителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tare_volume',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем тары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.CharField(max_length=50, verbose_name='Налог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.CharField(max_length=100, verbose_name='Уникальный идентификатор'),
        ),
    ]
