# Generated by Django 4.1.7 on 2023-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_receipt_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Временная метка'),
        ),
    ]
