# Generated by Django 4.1.7 on 2023-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_receipt_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='deviceId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор устройства'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='egais',
            field=models.BooleanField(blank=True, null=True, verbose_name='ЕГАИС'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='employeeId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор сотрудника'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='extras',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='infoCheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Информационный чек'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='paymentSource',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник оплаты'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shiftId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор смены'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='storeId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор магазина'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='totalDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма скидки'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='totalTax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма налога'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Версия'),
        ),
    ]
