# Generated by Django 4.1.7 on 2023-06-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_receipt_datetime_alter_receipt_deviceid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='token',
        ),
    ]
