# Generated by Django 4.1.7 on 2023-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_receipt_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='id_receipt',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID'),
        ),
    ]
