# Generated by Django 4.1.7 on 2023-06-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_productcategory_terminaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminaluser',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='UUID'),
        ),
    ]
