# Generated by Django 4.1.7 on 2023-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_product_alco_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.CharField(max_length=100, null=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
